### ISSUE TITLE
More Feedback

### ISSUE THREAD

**Issue by Morganmrose** [cartfisk/chickenParse#3]
Your code is clean and, as previously mentioned by another issue, I like the idea of the Twitter container as it helps organization. And while your code does contain some documentation, I feel as if it needs more, though it is good you cited your sources and mentioned honestly in your TweetContainerTest.java that you're not sure yet how these work. I think it would also be a good idea to include a bit more in your Readme in the future about what your code does and how it achieves the outcome, and more about what mentions/hashtags/etc are in relation to Twitter (I should do this to mine as well). While everyone in the class of course knows these things, other projects done in the future that are looked at by people who are unfamiliar with certain concepts would benefit from a more detailed Readme.

**Comment by cartfisk** [comment]
While I don't think an explanation of Twitter terminology in the readme is necessary (someone unfamiliar with Twitter would have no use for my project and should probably learn how Twitter works on their own before attempting to parse its data), I do agree that I should add more to my documentation.

I will reconstruct my readme making it explicitly clear that this project is used with Twitter data and add more about getting the project set up.

**Comment by cartfisk** [comment]
Readme updated!
