### ISSUE TITLE
separate tests from source code

### ISSUE THREAD

**Issue by sshilpika** [cartfisk/chickenParse#5]
You're basic structuring is good and the code itself is very well organized and more importantly
readable. However, it's always a better practice to have tests in a separate folder (instead of src/ have a test folder which holds all your tests).

**Comment by cartfisk** [comment]
I'm always a little shaky with file structure in projects– are there any considerations to make before moving files around? I believe I initially tried to put them in their own folder but Eclipse was being problematic, thinking they aren't supposed to be the same package.

**Comment by sshilpika** [comment]
Have you tried this structure
/src
&nbsp;&nbsp;&nbsp;/main --> contains source code
&nbsp;&nbsp;&nbsp;/test --> contains tests

**Comment by cartfisk** [comment]
Perfect, I had the structure right the first time but forgot to include appropriate imports! Thanks to @SalomonSmeke for bridging this gap for me. Committing momentarily.
