### ISSUE TITLE
Remove committed class files

### ISSUE THREAD

**Issue by sshilpika** [cartfisk/chickenParse#6]
Here's a link for git best practices: https://gist.github.com/SethRobertson/1540906/68feeabfe906ec1eb893e4fa45f402795ed6e62c#dont

**Comment by cartfisk** [comment]
Do you mean remove the generated classes in bin/chickenParse?

**Comment by sshilpika** [comment]
Yes, that's right! You should make sure that you do not commit anything that can be regenerated from what is already committed.

**Comment by cartfisk** [comment]
Makes sense! As far as actually doing this, I'm assuming I should edit the .gitignore? I've been needing to get familiar with these for a while. Now seems like a good time.

**Comment by sshilpika** [comment]
Yes, I usually look at the .gitignore from projects [here](https://github.com/LoyolaChicagoCode)

**Comment by cartfisk** [comment]
Updated gitignore and cleared old cached files that were erroneously uploaded initially.
Thanks to @jthompson18 for explaining cache clearing and how to do gitignores in SourceTree.
