### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by mgibbons2** [cartfisk/chickenParse#7]
First off, I would like to say that I really liked the organization of the classes and packages. It made it very easy to jump right into your code. As far as testing is concerned, you created a good amount of tests that will ensure that the project will not encounter any problems. The use of a container to hold your Arrays of strings made a lot of sense to me and I may be influenced to do the same. The only thing I can really think of to improve this would be to have your program ping the url and verify that you do get a response, that way you can avoid dead links. Right now you have a regular expression to very it, which works perfectly fine.

**Comment by cartfisk** [comment]
Checking for dead links is a good suggestion but as this project is only a component as opposed to a full-featured application, I think checking dead links would only be implemented if necessary. There are plenty of use cases where it is not necessary to know whether or not a link is dead or alive.
